import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Navbar from "../components/layout/Navbar";
import { AppSidebar } from "@/components/layout/Sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Room Radar | Dashboard",
  description: "Generated by create next app",
  icons: { icon: "/images/radar-icon.svg" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <html lang="en">
        <body className={`${poppins.variable} antialiased`}>
          <AppSidebar />
          <Navbar />
          {children}
        </body>
      </html>
    </SidebarProvider>
  );
}
